### ISSUE TITLE
Implements pedestrian crossing or remove associated icon file

### ISSUE THREAD

**Issue by Ettapp** [ABAPlan/abaplan-core#125]
Currently the file "passage.png" isn't used anywhere.

@jcavat What we should do ?

**Comment by jcavat** [comment]
Can you give me the link please

**Comment by Ettapp** [comment]
https://github.com/ABAPlan/abaplan-core/blob/master/src/app/editor/toolbar/img/passage.png

**Comment by Ettapp** [comment]
Must be an old asset, the pedestrian crossing is already implemented with this image: https://github.com/ABAPlan/abaplan-core/blob/master/src/app/editor/toolbar/img/pedestrian.png

The other pedestrian asset is useless too, the pull request #130 remove it.
