### ISSUE TITLE
Add restriction for scrolling (district/city map)

### ISSUE THREAD

**Issue by maximeburri** [ABAPlan/abaplan-core#29]
Nothing show in map if scroll is bad. To fix it :
- Disable tab **OR** auto-scroll to the minimum zoom if the map of clicked tab must be scrolled
- Don't scroll if current tab exceed minimum scroll

Where are the rules of minimum zoom/scroll for district map and city map ?

**Comment by jcavat** [comment]
I let you meditate about the best solutions

**Comment by maximeburri** [comment]
See editor.php
```
function showEditor(city) {
    var zoom = Editor.getZoom();
    if ((city && zoom < 16) || (!city && zoom < 18)){
        alert("Merci de zoomer plus");
    }else{
        DrawTools.setFillSize(zoom);
        Editor.setMapCursor(false);
        Editor.showEditor(city, onEditorReady);

        $('#cityEdition').hide();
        $('#districtEdition').hide();
        $('#zoneSelection').show();
        $('#print').show();
        $('#save').show();
        $('#drawingMenu').show();
    }
};
```

**Comment by jcavat** [comment]
Maybe we should change the background image of the navigator when we are up to the threshold ?
