### ISSUE TITLE
Pedestrians don't have same size and aren't precise enough

### ISSUE THREAD

**Issue by maximeburri** [ABAPlan/abaplan-core#35]
Pedestrians don't have same size due to zoom.

Draw pedestrian (1), dezoom, draw pedestrian (2). dezoom

![capture du 2016-12-07 13-23-16](https://cloud.githubusercontent.com/assets/5551924/20967582/81ac052a-bc80-11e6-80ca-c7fd42c416d6.png)

**Comment by jcavat** [comment]
![apres](https://cloud.githubusercontent.com/assets/1701806/21428659/81cb7a86-c85b-11e6-9c0b-883f7f4ce44a.jpg)

**Comment by jcavat** [comment]
Improve pedestrians pathways algorithms
