### ISSUE TITLE
Define a strategy for credentials

### ISSUE THREAD

**Issue by jcavat** [ABAPlan/abaplan-core#8]

**Comment by maximeburri** [comment]
Front-end applications do not have access back-end environment variables.

Solution of this article [How to configure your AngularJS application using environment variables](http://www.jvandemo.com/how-to-configure-your-angularjs-application-using-environment-variables/)  is to create new javascript file `env.js` and load this file on app component html `<script src="env.js"></script>`.

To not commit this file, create `example.env.js` for example. Each developper must be copy to `env.js` once time and add credentials.  
In .gitignore :


Questions : 
 - In which folder put env.js ? In shared ?
 -

**Comment by jcavat** [comment]
And what happened when we push into production ?

**Comment by jcavat** [comment]
Maybe we should consider this topic if we want to push the old project with credentials ?
