### ISSUE TITLE
Loading state image still running when an OSM layer has loaded

### ISSUE THREAD

**Issue by jcavat** [ABAPlan/abaplan-core#81]
Maybe due to #80.

How to reproduce:

1. Load a map
2. Change immediately the layer to OSM

**Comment by jcavat** [comment]
Network inspection shows that the layer is still waiting for resources... Even if we switch to OSM layer

**Comment by maximeburri** [comment]
To fix that we need to use layer load/finish events instead of map.

Layers events do not seem to work :
https://github.com/ABAPlan/abaplan-core/blob/fix-loading-%2381/app/core/map.ts#L66-L92

**Comment by maximeburri** [comment]
Layers events seem to work in layer-add : https://github.com/ABAPlan/abaplan-core/blob/fix-loading-%2381/app/core/map.ts#L56-L84

**Comment by jcavat** [comment]
procrastination ?

**Comment by maximeburri** [comment]
Issue closed. 
Loading image is not shown anymore, but layer not visible are always loading images (in network inspection). Nothing to do.. `layer.suspend()`, `layer.hide()` or `layer.setVisibility(false)` don't stop these requests..

**Comment by jcavat** [comment]
I think it's normal because each request involve a response.

**Comment by maximeburri** [comment]
Not necessarily, because if you go in "City", after "Osm" after "City", requests of first "City" is canceled.
![image](https://cloud.githubusercontent.com/assets/5551924/24654414/ca609cca-1939-11e7-8b9f-9e37c00a7059.png)
